import { Colors } from '@/constants/theme';
import { getResponsiveDimensions, isDesktop } from '@/utils/responsive';
import { StyleSheet } from 'react-native';

const dimensions = getResponsiveDimensions();

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
    paddingHorizontal: dimensions.paddingHorizontal,
    paddingTop: isDesktop ? 80 : 60,
    ...(isDesktop && {
      justifyContent: 'center',
      alignItems: 'center',
    }),
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: Colors.light.primary,
    marginBottom: 8,
  },
  logoSubtext: {
    fontSize: 16,
    color: Colors.light.secondary,
    fontWeight: '500',
  },
  formContainer: {
    flex: 1,
    justifyContent: 'center',
    ...(isDesktop && {
      width: dimensions.formWidth,
      maxWidth: dimensions.containerMaxWidth,
      backgroundColor: Colors.light.background,
      borderRadius: 16,
      padding: 48,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  title: {
    fontSize: isDesktop ? 32 : 28,
    fontWeight: 'bold',
    color: Colors.light.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: isDesktop ? 18 : 16,
    color: Colors.light.icon,
    textAlign: 'center',
    marginBottom: isDesktop ? 40 : 32,
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.light.text,
    marginBottom: 8,
  },
  input: {
    backgroundColor: Colors.light.inputBackground,
    borderWidth: 1,
    borderColor: Colors.light.border,
    borderRadius: 12,
    paddingHorizontal: isDesktop ? 20 : 16,
    paddingVertical: isDesktop ? 18 : 14,
    fontSize: isDesktop ? 18 : 16,
    fontFamily: 'System',
    color: Colors.light.text,
    ...(isDesktop && {
      minHeight: 56,
    }),
  },
  inputFocused: {
    borderColor: Colors.light.primary,
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  errorText: {
    color: Colors.light.error,
    fontSize: 12,
    marginTop: 4,
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-end',
    marginTop: 8,
  },
  forgotPasswordText: {
    color: Colors.light.primary,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'System',
  },
  primaryButton: {
    backgroundColor: Colors.light.primary,
    borderRadius: 12,
    paddingVertical: isDesktop ? 20 : 16,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    ...(isDesktop && {
      minHeight: 56,
    }),
  },
  primaryButtonText: {
    color: Colors.light.background,
    fontSize: isDesktop ? 18 : 16,
    fontWeight: '600',
    fontFamily: 'System',
  },
  googleButton: {
    backgroundColor: Colors.light.background,
    borderWidth: 1,
    borderColor: Colors.light.border,
    borderRadius: 12,
    paddingVertical: isDesktop ? 20 : 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    ...(isDesktop && {
      minHeight: 56,
    }),
  },
  googleButtonText: {
    color: Colors.light.text,
    fontSize: isDesktop ? 18 : 16,
    fontWeight: '500',
    fontFamily: 'System',
    marginLeft: 12,
  },
  installSection: {
    marginTop: 18,
    borderWidth: 1,
    borderColor: Colors.light.border,
    borderRadius: 12,
    padding: 12,
    backgroundColor: Colors.light.inputBackground,
  },
  installTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.light.text,
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'System',
  },
  installButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: Colors.light.primary,
    marginBottom: 8,
  },
  installPwaButton: {
    backgroundColor: Colors.light.secondary,
    marginBottom: 6,
  },
  installButtonText: {
    color: Colors.light.background,
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'System',
  },
  installHint: {
    fontSize: 12,
    color: Colors.light.icon,
    textAlign: 'center',
    fontFamily: 'System',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
  },
  linkText: {
    color: Colors.light.icon,
    fontSize: 14,
    fontFamily: 'System',
  },
  link: {
    color: Colors.light.primary,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'System',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: Colors.light.background,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'System',
    marginLeft: 8,
  },
  pickerInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerText: {
    fontSize: isDesktop ? 18 : 16,
    fontFamily: 'System',
    color: Colors.light.text,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: Colors.light.border,
    borderRadius: 4,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: Colors.light.primary,
    borderColor: Colors.light.primary,
  },
  checkboxText: {
    flex: 1,
    fontSize: 14,
    color: Colors.light.text,
    fontFamily: 'System',
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: Colors.light.background,
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '70%',
    ...(isDesktop && {
      width: 400,
    }),
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.light.text,
    marginBottom: 16,
    textAlign: 'center',
    fontFamily: 'System',
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
  },
  modalItemText: {
    fontSize: 16,
    color: Colors.light.text,
    fontFamily: 'System',
  },
  modalCloseButton: {
    marginTop: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalCloseText: {
    fontSize: 16,
    color: Colors.light.primary,
    fontWeight: '600',
    fontFamily: 'System',
  },
});
